name: Simple ML CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  train_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model and log to MLflow
        run: |
          python train.py
          ls -R
          ls -R artifacts

      - name: Run tests (pytest)
        run: pytest -q

      - name: Upload model artifact
        uses: actions/upload-artifact@v4
        with:
          name: model-artifact
          path: artifacts/model.pkl

  build_and_push:
    needs: train_and_test
    runs-on: ubuntu-latest
    if: ${{ needs.train_and_test.result == 'success' && github.ref == 'refs/heads/main' }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: model-artifact
          path: artifacts

      - name: Show artifacts
        run: ls -R artifacts

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/simple-reg-app:latest .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/simple-reg-app:latest

      - name: Upload image info
        run: echo "image=ghcr.io/${{ github.repository_owner }}/simple-reg-app:latest" > image.txt
      - uses: actions/upload-artifact@v4
        with:
          name: docker-info
          path: image.txt
